function [params] = get_params(modality)
%GET_PARAMS

switch modality
    case "lfp"
        params.roi_names = {'left','right'}; 
    case "eeg"
        params.roi_names = {'F3','AF3','C3','CP1'};
    case "stc"
        params.roi_names = {
            "rostralanteriorcingulate-lh", ...
            "caudalanteriorcingulate-lh", ...
            "postcentral-lh", ...
            "insula-lh", ...
            "superiorfrontal-lh", ...
            "medialorbitofrontal-lh",...
            "rostralanteriorcingulate-rh", ...
            "caudalanteriorcingulate-rh", ...
            "postcentral-rh", ...
            "insula-rh", ...
            "superiorfrontal-rh", ...
            "medialorbitofrontal-rh"
        };
end 

params.fbands = struct(...
    'theta', [4, 8], ...    
    'alpha', [8, 13], ...    
    'beta', [13, 30], ...        
    'low_gamma', [30, 58.5], ... 
    'high_gamma', [61.5, 100] ...  
);

params.Fs=600; % sampling rate

%% Thresholds for binarizing pain
params.pain_threshold = 4;
params.gap = 1;
params.high_pain_threshold = 7; % threshold for train trials

%% Training parameters
params.Tbin                =       2; % seconds before and after events
params.train_plot_flag     =       0; % plot or not
params.log_transform_flag  =       1; % instead of mean, helps to compare high and low freqs
params.fft_flag            =       0; % fft instead of mtspecgram, maybe defunct?
params.folds               =       5; % number of train trials to attempt

end

